import Head from "next/head";
import Image from "next/image";
import cn from "clsx";

import { Text } from "@/components/text";

import profilePic from "../../public/profile.jpg";

import styles from "@/styles/home.module.css";
import { Typewriter } from "@/components/typewriter";
import { useState } from "react";

export default function Home(): JSX.Element {
  const [showHighlight, setShowHighlight] = useState<boolean>(false);
  const [showSubtitle, setShowSubtitle] = useState<boolean>(false);

  return (
    <>
      <Head>
        <title>Rafael Nunes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <section className={styles.section}>
          <header>
            <Text as="h1" className="hidden">
              Início
            </Text>
          </header>
          <Image
            src={profilePic}
            alt="Foto do autor"
            width={300}
            height={300}
            className={styles.img}
          />
          <div className={styles.div}>
            <Typewriter
              as="h1"
              text="Olá, meu nome é "
              onFinish={() => {
                setShowHighlight(true);
              }}
              className={styles.h1}
            />
            {showHighlight ? (
              <Typewriter
                as="h1"
                text="Rafael"
                onFinish={() => {
                  setShowSubtitle(true);
                }}
                className={cn(styles.h1, styles.strong)}
                blinkAtEnd
              />
            ) : null}
          </div>
        </section>
        {showSubtitle ? (
          <Text as="span" className={styles.span}>
            Desenvolvedor Front-end
          </Text>
        ) : (
          <div className={styles.empty} />
        )}
      </main>
    </>
  );
}
