import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";

import { Text } from "@/components/text";
import profilePic from "../../public/profile.jpg";

const inter = Inter({ subsets: ["latin"] });
import styles from "@/styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Rafael Nunes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <section className={styles.section}>
          <Text as="header">
            <Text as="h1" className="hidden">
              Início
            </Text>
          </Text>
          <Image
            src={profilePic}
            alt="Foto do autor"
            width={300}
            height={300}
            className={styles.img}
          />
          <Text as="h1" className={styles.h1}>
            Olá, meu nome é{" "}
            <Text as="strong" className={styles.strong}>
              Rafael
            </Text>
          </Text>
        </section>
        <Text as="span" className={styles.span}>
          Desenvolvedor Front-end
        </Text>
      </main>
    </>
  );
}
